sudo: required
services:
  - docker
script:
  - docker build -t wisehackermonkey/react-example2 .
  - docker images wisehackermonkey/react-example2

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push wisehackermonkey/react-example2
  on:
    branch: master